### ISSUE TITLE
Konfiguracja w języku YAML

### ISSUE THREAD

**Issue by SlimaKCoder** [SlimaKCoder/projectQ-Reloaded#4]
@TheMolkaPL @Wruczek @Co0sh
Co sądzicie zapisywaniu konfiguracji w języku YAML? Myślę, że dla typowego administratora MC język YML będzie bardzo przyjazny w porównaniu do tablic i zmiennych PHP. Jedyną wadą jest luka bezpieczeństwa, ale można ją łatwo załatać przy konfiguracji "routes".

**Comment by TheMolkaPL** [comment]
:+1:

**Comment by Wruczek** [comment]
Ja jednak wolałbym normalne pliki z tablicami php.

**Comment by SlimaKCoder** [comment]
@Wruczek 
Przykładowy zapis w YAML:
```YAML
hostname: localhost
database: projectq
port: 3306
username: projectq
password: projectq
```
To samo w PHP:
```php
const CONFIG = [
    'hostname' => 'localhost',
    'database' => 'projectq',
    'port' => 3306,
    'username' => 'projectq',
    'password' => 'projectq
];
```
